### ISSUE TITLE
branding, naming

### ISSUE THREAD

**Issue by pdurbin** [opendp/dp-wizard#115]
Having watched the pain of Perl 6 getting renamed to something without a number (Raku), I'm not sure it's wise to have a number in the name of a piece of software.

It would also be a way to avoid having roman numerals in the name of the software.

So, can we just call it DP Creator? It's a rewrite. That's ok. 😄

**Comment by mccalluc** [comment]
I'm not sure exactly what your proposal is. This sort of depends on whether we're completely abandoning the https://github.com/opendp/dpcreator codebase.
- If we are, great, let's rename this to plain `dp-creator`, add a note on that repo pointing here, and archive it.
- If we aren't, then I really don't think we want two projects that are active at the same time that are only distinguished by punctuation in the repo name.
- I believe it was the right decision to start a new repo: Dealing with a history of issues that applied to an entirely unrelated codebase would be a distraction.

Would plain `dpc` be ok? Or change it to `dp-helper`?

Here's the thread with Annie where this was decided.

> anniewu
>   Sep 18th at 12:36 PM
> Should we name the new one DPC2? :smile:
> 4 replies
> 
> 
> Chuck McCallum
>   [Sep 18th at 1:02 PM](https://opendp.slack.com/archives/C02N758BK3J/p1726678939936159?thread_ts=1726677416.924629&cid=C02N758BK3J)
> No strong preference on the particular name, but agree that a new name and a new repo would be good. A number in the name might get confusing when/if there successive releases. Perhaps dp-creator-lite for repo name, "DP-Creator-Lite" in text? (compare with https://vega.github.io/vega-lite/)
> 
> anniewu
>   Sep 18th at 1:30 PM
> Lite sounds like an unpaid version with limited features that users can try and decide whether to buy the full version. :smile:   (edited) 
> [1:31](https://opendp.slack.com/archives/C02N758BK3J/p1726680695118399?thread_ts=1726677416.924629&cid=C02N758BK3J)
> DP Creator Returns :smile:
> 
> Chuck McCallum
>   [Sep 18th at 1:57 PM](https://opendp.slack.com/archives/C02N758BK3J/p1726682244836659?thread_ts=1726677416.924629&cid=C02N758BK3J)
> Ok, I think it's going to be hard to find an adjective that describes what we're trying to do here (refocus on some core set of user needs) without suggesting that it's somehow less than the original. Roman numerals might avoid confusion with version numbers: dp-creator-ii for repo name, "DP Creator II" in text? And down the road, "DP Creator II v0.1.2" etc.
> I could stub out the repo if that sounds ok?

**Comment by pdurbin** [comment]
A fresh repo makes complete sense. We're talking about a complete rewrite.

I would suggest:

- Rename https://github.com/opendp/dpcreator to https://github.com/opendp/dpcreator-classic (or whatever) and update the README to point to the new repo, this repo. Explain that a rewrite is underway.
- Remove "ii" from the name of this repo and branding. In a few years, no one will care that there was ever a different, earlier version, a rewrite happened. No one will use the old version. If you like the DP Creator name, take it over for this project. Having a number, even Roman numerals, in the name of a piece of software, is odd. Avoid.

If you DON'T like the name DP Creator, then I can probably suggest something else.

Naming is hard! I totally get why you settled on whatever name and got started. However, the earlier you right the ship the better.

**Comment by mccalluc** [comment]
That sounds fine to me. Let me loop in Ceilyn to see if what stakeholders need to be involved.

**Comment by anniewu332** [comment]
I remember we arrived at the DP Creator name through a small naming contest within the team (also around Halloween that year!)  We can do another one if it sounds like fun.

**Comment by mccalluc** [comment]
@anniewu332 , that is not the route I'd prefer to go. If this is essentially the same project, let's keep a related name to make that clear. We all have a lot on our plates, and I'd prefer that we don't distract more people with a decision that a small group of stakeholders should be able to settle.

**Comment by mccalluc** [comment]
Done!

**Comment by pdurbin** [comment]
I'm still glad we renamed the app 🎉  and I still think having a number in the name is suboptimal 👎  but I thought of a couple more examples. The complete list:

- Perl 6 (renamed to [Raku](https://en.wikipedia.org/wiki/Raku_(programming_language)))
- [ggplot2](https://en.wikipedia.org/wiki/Ggplot2)
- [IrcII](https://en.wikipedia.org/wiki/IrcII)
