### ISSUE TITLE
Repository Setup

### ISSUE THREAD

**Issue by cmbz** [opendp/dp-wizard#90]
## Overview
- Tasks related to setting up the repository and CI/CD workflows

## Issues
- [ ] https://github.com/opendp/dp-creator-ii/issues/60
- [x] #104
- [x] #110
- [ ] #111
- [x] #112
- [ ] #113

## Dependencies
- None

## Related
- https://github.com/IQSS/dataverse-pm/issues/337

**Comment by mccalluc** [comment]
Done enough. Remaining issues can be recategorized.
