### ISSUE TITLE
Define Analysis Tab

### ISSUE THREAD

**Issue by cmbz** [opendp/dp-wizard#93]
## Overview
- Tasks associated with implementing the DP Creator 2 `Define Analysis` tab 

## Issues
- [x] #94
- [x] https://github.com/opendp/dp-creator-ii/issues/83
- [x] https://github.com/opendp/dp-creator-ii/issues/84
- [x] Implement epsilon slider
  - [x] https://github.com/opendp/dp-creator-ii/issues/25
- [x] #124
- [x] #127
- [x] #130
- [x] #132
- [x] #131
- [x] #138
- [ ] #174

## Dependencies
- None

## Related
- https://github.com/IQSS/dataverse-pm/issues/337

**Comment by mccalluc** [comment]
Done
