### ISSUE TITLE
Improve page UI/UX

### ISSUE THREAD

**Issue by cmbz** [opendp/dp-wizard#94]
## Overview
- Tasks to improve the UI/UX of the `Define Analysis` page

## Issues
- [ ] https://github.com/opendp/dp-creator-ii/issues/82
- [x] #128
- [x] #133
- [x] #136

## Dependencies
- None

## Related
- https://github.com/opendp/dp-creator-ii/issues/93

**Comment by mccalluc** [comment]
Done
