### ISSUE TITLE
Choose approach to perform analysis

### ISSUE THREAD

**Issue by cmbz** [opendp/dp-wizard#96]
## Overview
- Choose the best approach to perform analysis. Two options include: 1) generate and execute code, or 2) generate and execute notebook
 
## Issues
- [x] https://github.com/opendp/dp-creator-ii/issues/36

## Dependencies
- None

## Related
- https://github.com/opendp/dp-creator-ii/issues/95

**Comment by mccalluc** [comment]
The notebook is what we execute, because it's an artifact which wraps up both input and output. This is working well enough.
