### ISSUE TITLE
Define non-notebook outputs

### ISSUE THREAD

**Issue by cmbz** [opendp/dp-wizard#98]
## Overview
- Define the format of non-notebook outputs, such as comma-delimited files

## Issues
- [ ] https://github.com/opendp/dp-creator-ii/pull/69
- [x] #108

## Dependencies
- None

## Related
- https://github.com/opendp/dp-creator-ii/issues/95

**Comment by mccalluc** [comment]
There is a format, and until there is feedback, we'll assume it's good enough.
